### ISSUE TITLE
[DDRC-24] Error: cannot open device with vendor id 0x2752 and product id 0x11

### ISSUE THREAD

**Issue by HansVanEijsden** [mrene/node-minidsp#8]
After executing ` minidsp monitor` I get this error:

```
iMac-van-Hans-van-Eijsden:~ hans$ minidsp monitor
/usr/local/lib/node_modules/minidsp/node_modules/node-hid/nodehid.js:54
    this._raw = new (Function.prototype.bind.apply(binding.HID,
                ^

Error: cannot open device with vendor id 0x2752 and product id 0x11
    at new HID (/usr/local/lib/node_modules/minidsp/node_modules/node-hid/nodehid.js:54:17)
    at new USBTransport (/usr/local/lib/node_modules/minidsp/src/transport/usb.js:15:27)
    at device (/usr/local/lib/node_modules/minidsp/minidsp.js:57:43)
    at Command.program.command.description.action (/usr/local/lib/node_modules/minidsp/minidsp.js:119:13)
    at Command.listener (/usr/local/lib/node_modules/minidsp/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/local/lib/node_modules/minidsp/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/minidsp/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/minidsp/minidsp.js:152:9)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
```

It reminds me of something. I use the DDRC-24 and not the MiniDSP2x4HD this software was made for, although the MiniDSP2x4HD can be upgraded to the DDRC-24 via a simple software upgrade; it's the same piece of hardware.
The output of `minidsp devices` is empty and `minidsp -V` gives version 1.0.3.

**The vendor id of my DDRC-24 is `0x2752` and the product id is `0x0044`.**
Do you think there's a possibility to make it working with the DDRC-24 (if I'm not asking too much), if that's really the error I have?
Normally I hate opening tickets for this kind of things, but I'm just too curious and would love to have it working. 😃 Thanks!

**Comment by HansVanEijsden** [comment]
Update: I edited src/constants.js and changed `USB_PID: 0x0011` to `USB_PID: 0x0044` and it works, more or less! 👍 

```
iMac-van-Hans-van-Eijsden:node-minidsp hans$ node minidsp.js devices
IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/PRT3@14300000/DDRC-24@14300000/IOUSBHostInterface@4/IOUSBHostHIDDevice@14300000,4	DDRC-24
iMac-van-Hans-van-Eijsden:node-minidsp hans$ node minidsp.js monitor
(node:65904) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2 [▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇] 0.0 dBFS
iMac-van-Hans-van-Eijsden:node-minidsp hans$ node minidsp.js mute
(node:65912) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
iMac-van-Hans-van-Eijsden:node-minidsp hans$ node minidsp.js mute disable
(node:65914) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

Everything works except the web interface and monitor. They don't run because of that DeprecationWarning unfortunately, but mute and volume are working (and oh, how much I would love to have a `mute status` command). 😉

**Comment by mrene** [comment]
Glad to hear it works - those warnings are due to a newer version of node where things got deprecated, but you can launch node with [--no-warnings](https://nodejs.org/api/cli.html#cli_no_warnings) to silence them (or set the [NODE_NO_WARNINGS](https://nodejs.org/api/cli.html#cli_node_no_warnings_1) environment variable).

**Comment by HansVanEijsden** [comment]
Great! Thank you again! 👍🏻
